### PR TITLE
Add error hint when block is invalid

### PR DESCRIPTION
**Pull request by kstvr32**
# Changes

## Adds Mode switches to hologram projector GUI

Currently there are two settings, showing errors and placing GT hatches. The show error setting is always enabled, the GT hatch setting is only enabled when GT is loaded.

### GT Enabled

Standard           |  Settings Enabled
:-------------------------:|:-------------------------:
image  |  image

### GT Disabled
Standard           |  Settings Enabled
:-------------------------:|:-------------------------:
image  |  image

## Adds structure error mode

When creating hints for a structure check, checks the validity of the block. If a block is not valid it makes the hint as an error which makes it render on top and turn red. 

This is implemented by expanding the `IStructureElement<T>` interface with `boolean couldBeValid(T t, World world, int x, int y, int z, ItemStack trigger)`. This is different than the `check(...)` function because it should be side effect free and depend on the trigger item tiers. It should return `false` when the current block is definitely not valid, but returns `true` if the block could be valid (or we don't know). If the structure element `couldBeValid(...)==false`, the hint will be tinted red and show through blocks.

The default `couldBeValid(...)` implementation always returns `true`. I have updated the utility methods where we have better information. I will have a separate PR in GTNewHorizons/GT5-Unofficial that updates the `IStructureElement<T>` implementations there.

Most of the checks are implemented in GTNewHorizons/GT5-Unofficial#3254

#### Finding wrong tier coil on DTPF
errorHintDemo

#### Highlighting blocks to upgrade EOH
errorHintDemo2

### CODE REVIEW

**Comment by Glease** [comment]
check() is neither stateless nor sideeffect free. It frequently depends on machine state (and will mutate it!). There are also necessary setup before all check() on any IStructureElement are to be called. this will require further testing to prove it won't cause false negatives and/or other undesirable side effects

some errorprone scenario that immediately come to mind
* mixed ofBlocksTiered, and the intended tier is not the first tier: might give wrong hint
* client side memory leak on hatches: call hint(), then remove the hatches, and the reference to the hatch might persist in the client side multiblock controller's hatch list

I have not tested these yet and will do so later. Any help would be much appreciated.

**Comment by kstvr32** [comment]
I see, yeah the blocks tiered is a problem on some multis (works with channels set, but not default channel). I will look to see if there is a decent fix.

Marking PR as draft while doing so.

**Comment by kstvr32** [comment]
Updated and no longer uses `check` function.

**Review by Glease — APPROVED** [review]
I'm not extremely happy with how gt_no_hatch is hardcoded into structurelib code, but I guess this is for now a reasonable compromise.

**Comment by kstvr32** [comment]
This PR uses https://github.com/GTNewHorizons/GT5-Unofficial/pull/3254 for GT compat and implementation of error checking. 

I'll take another look and un-draft it later.

**Comment by kstvr32** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3254 is ready for review and should bring structure error highlighting to nearly all GT multis.

**Pull request merged**
