### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by leagris**
- updateBuildScript
- spotlessApply

### CODE REVIEW

**Comment by Glease** [comment]
there is a parallel PR #6 and this'd cause huge merging pain - can we hold this off for a while?

**Comment by leagris** [comment]
> there is a parallel PR #6 and this'd cause huge merging pain - can we hold this off for a while?

Sure, feel free to eventually close this and do the same on your side after you are done with PR #6

**Comment by boubou19** [comment]
i converted this to a draft so it won't end up accidentally being merged

**Comment by Glease** [comment]
Superseded by #6

**Pull request closed without merging**
